# 接続コマンド
# ansible-playbook -i raspi-host -u pi --ask-pass  nfs.yml -vvv
---
- hosts: all
  become: yes
  remote_user: pi
  gather_facts: no

  vars:
    LOCALE: "ja_JP.UTF-8"
    TIMEZONE: "Asia/Tokyo"
    XKBLAYOUT: ”jp”

  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: yes

    - name: apt install
      apt:
        name:
          - nfs-kernel-server

    # 5分で終わらせるNFSファイル共有 https://qiita.com/rikudai/items/f9900e4865ce25a8464e
    - name: mkdir nfs
      file:
        path: /mnt/public
        state: directory

    - name: permission
      blockinfile:
        dest: /etc/dhcpcd.conf
        content: |
          # /etc/exports: the access control list for filesystems which may be exported
          #       to NFS clients.  See exports(5).
          #
          # Example for NFSv2 and NFSv3:
          # /srv/homes       hostname1(rw,sync,no_subtree_check) hostname2(ro,sync,no_subtree_check)
          #
          # Example for NFSv4:
          # /srv/nfs4        gss/krb5i(rw,sync,fsid=0,crossmnt,no_subtree_check)
          # /srv/nfs4/homes  gss/krb5i(rw,sync,no_subtree_check)
          #
          /srv/nfs 192.168.3.0/24(rw,sync,no_subtree_check,no_root_squash)

    # - name: Deny all access to port 2049
    #   ufw:
    #     rule: allow
    #     port: "2049"

    - name: Make sure a service is running
      systemd:
        name: rpcbind
        state: started
        enabled: yes

    - name: httpd a service is running
      systemd:
        name: nfs-server
        state: started
        enabled: yes
