client_config_backend: settings
client_config:
  client_id: 351810026453-s74pkjr2lkeofbvns5i4ucjaksei0cgf.apps.googleusercontent.com
  client_secret: J8iFpTgnCW718RQZ4QSOSka-

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install