# 接続コマンド
# ansible-playbook -i raspi-host -u pi --ask-pass youtube-server/youtube-server.yml -vvv
---
- hosts: all
  become: yes
  remote_user: pi
  gather_facts: no

  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: yes

    - name: apt install
      apt:
        name:
          - python3
          - python3-pip
          - opam
          - mccs
          - ffmpeg

    - name: Remove aspcud package
      apt:
        name: aspcud
        state: absent

    - name: Install youtube
      pip:
        name:
          - youtube_dl
        executable: pip3

    - name: copy python
      copy:
        src: ./get.py
        dest: /youtube

    - name: copy list file
      copy:
        src: ./list.csv
        dest: /youtube

    # 今のところ手動(実行長いので注意)https://qiita.com/teamhimeH/items/9910d648da0a9ff09946
    # opam init --solver=mccs
    #    opam switch create 4.09.0
    #    eval $(opam env)
    #    opam depext google-drive-ocamlfuse
    #    opam install google-drive-ocamlfuse

    - name: cron設定
      become: True
      cron:
        name: youtube dl
        minute: "0"
        hour: "3"
        job: "python3 /youtube/get.py 1 >> /youtube/log/exec.log  2>> /youtube/log/error.log"
        state: present
        user: pi