# 接続コマンド
# ansible-playbook -i raspi-host -u pi --ask-pass  youtube-server/youtube-server.yml -vvv
---
- hosts: all
  become: yes
  remote_user: pi
  gather_facts: no

  vars:
    LOCALE: "ja_JP.UTF-8"
    TIMEZONE: "Asia/Tokyo"
    XKBLAYOUT: ”jp”

  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: yes

    - name: apt install
      apt:
        name:
          - python3
          - python3-pip

    - name: Install youtube
      pip:
        name:
          - youtube_dl
          - PyDrive
        executable: pip3

    - name: mkdir youtube
      file:
        path: /youtube/videos
        state: directory
        mode: 0777

    - name: copy python
      copy:
        src: ./youtube-dl.py
        dest: /youtube
